### ISSUE TITLE
Handle lack of usernames better

### ISSUE THREAD

**Issue by adeebshihadeh** [commaai/connect-app#12]
New accounts don’t have a way to set a username, but the design seems to assume each user has one. When it falls back to email, it looks like a bug. Maybe we should always use email and just remove the first at symbol?
![473986A0-13B2-4BFB-84CA-DCD0B59E03C1](https://user-images.githubusercontent.com/8762862/111058311-a40dae00-8442-11eb-9a9f-51ece371b665.jpeg)

**Comment by jwooning** [comment]
Fixed on #15

simply always shows email
