### ISSUE TITLE
[android] QR scan never succeeds

### ISSUE THREAD

**Issue by byxorna** [commaai/connect-app#16]
Attempting to pair with a C2 via QR code never succeeds. The camera vibrates and flickers a black screen with a spinner, but immediately returns to the camera scan intent, with no indication of an error message. 

Device: Android 11 (and android 10), OnePlus 7Pro

**Comment by jwooning** [comment]
This will be fixed in the next release.

The problem was that it detects some other type of barcode, so for now, if you keep trying it should eventually pair. Maybe using some different lighting or varying the distance can increase the possibility of it pairing correctly.

**Comment by TKassis** [comment]
I'm having the same issue with my Google Pixel 4a. I cannot pair using the QR code no matter what I try. Is there another way we can pair? In the meantime, is there a way to link Explorer to our Comma Two without having to do it through the app?

I don't get a black screen or spinner, but the QR scan never happens and if I get too close it seems Connect is not using the phone's focus so it doesn't focus.

**Comment by Serenity888** [comment]
Having the same issue with an iPhone 12 Pro. Camera sees qr, vibrates, then rejects it and returns to "scan qr". By that time the qr disappears from the comma screen. 
Is there a manual method to pair?

**Comment by TKassis** [comment]
I ended up having to email suppot@comma.ai and they manually paired it for me.

**Comment by jwooning** [comment]
This specific issue should be fixed, other issues can still occur, see #26
