### ISSUE TITLE
Cancelling Comma Prime UI issue

### ISSUE THREAD

**Issue by kito408** [commaai/connect-app#3]
The UI presents the "sorry to see you cancel screen" with a back button "<" icon on the top left and a CANCEL button.  To me the cancel button means cancel the request to cancel comma prime command, but the comma connect app uses the cancel button to means proceed with the cancellation. It would be better if the app had a button like "YES I I WISH TO CANCEL COMMA PRIME" and another button "NO I WANT TO KEEP COMMA PRIME". or something like that.

**Comment by jwooning** [comment]
prime settings are no longer in connect
